# =============================================================================
# Outputs — surfaced to the operator and serialised into the repo-root .env.
# =============================================================================

# --- Resource group ---
output "resource_group_name" {
  description = "Resource group name."
  value       = azurerm_resource_group.rg.name
}

# --- Foundry ---
output "foundry_endpoint" {
  description = "Content Understanding endpoint (set as APP_CONTENT_UNDERSTANDING_ENDPOINT)."
  value       = module.foundry_resource.endpoint
}

output "foundry_resource_name" {
  description = "Foundry AI Services account name."
  value       = module.foundry_resource.name
}

output "foundry_project_name" {
  description = "Foundry project name."
  value       = module.foundry_project.name
}

# --- Model deployment names ---
output "gpt52_deployment_name" {
  description = "Deployment name for gpt-5.2."
  value       = module.foundry_resource.gpt52_deployment_name
}

output "gpt41_deployment_name" {
  description = "Deployment name for gpt-4.1."
  value       = module.foundry_resource.gpt41_deployment_name
}

output "gpt41_mini_deployment_name" {
  description = "Deployment name for gpt-4.1-mini."
  value       = module.foundry_resource.gpt41_mini_deployment_name
}

output "embedding_deployment_name" {
  description = "Deployment name for text-embedding-3-large."
  value       = module.foundry_resource.embedding_deployment_name
}

# --- Observability ---
output "appinsights_connection_string" {
  description = "Application Insights connection string."
  value       = module.app_insights.appinsights_connection_string
  sensitive   = true
}

# =============================================================================
# .env writer — emits the repo-root .env on every apply.
# Existing .env (if any) is moved aside to .env.bak before overwrite.
# =============================================================================

locals {
  env_content = <<-EOT
    # Auto-generated by Terraform — do not edit manually.
    # Source: infra/non-private/outputs.tf -> local_file.env

    # Pro Mode + Content Understanding
    APP_CONTENT_UNDERSTANDING_ENDPOINT=${module.foundry_resource.endpoint}
    APP_ENV=dev

    # Model deployments
    APP_CU_PRO_COMPLETION_DEPLOYMENT=${module.foundry_resource.gpt52_deployment_name}
    APP_CU_COMPLETION_DEPLOYMENT=${module.foundry_resource.gpt41_mini_deployment_name}
    GPT52_MODEL_DEPLOYMENT=${module.foundry_resource.gpt52_deployment_name}
    GPT41_MODEL_DEPLOYMENT=${module.foundry_resource.gpt41_deployment_name}
    GPT41_MINI_MODEL_DEPLOYMENT=${module.foundry_resource.gpt41_mini_deployment_name}
    EMBEDDING_MODEL_DEPLOYMENT=${module.foundry_resource.embedding_deployment_name}

    # Foundry resource references
    FOUNDRY_ENDPOINT=${module.foundry_resource.endpoint}
    FOUNDRY_RESOURCE_NAME=${module.foundry_resource.name}
    FOUNDRY_PROJECT_NAME=${module.foundry_project.name}

    # Azure identity / RG
    AZURE_SUBSCRIPTION_ID=${data.azurerm_subscription.current.subscription_id}
    AZURE_TENANT_ID=${module.app_registration.tenant_id}
    AZURE_RESOURCE_GROUP=${azurerm_resource_group.rg.name}

    # Workshop service principal (used by DefaultAzureCredential)
    AZURE_CLIENT_ID=${module.app_registration.client_id}
    AZURE_CLIENT_SECRET=${module.app_registration.client_secret}

    # Observability
    APPINSIGHTS_CONNECTION_STRING=${module.app_insights.appinsights_connection_string}
    LOG_ANALYTICS_WORKSPACE_ID=${module.app_insights.law_workspace_id}
  EOT

  env_path = "${path.module}/../../.env"
}

# Back up any existing .env to .env.bak before we overwrite it.
resource "terraform_data" "env_backup" {
  triggers_replace = {
    env_sha = sha1(local.env_content)
  }

  provisioner "local-exec" {
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-EOT
      $target = "${local.env_path}"
      if (Test-Path $target) {
        Copy-Item -Path $target -Destination "$target.bak" -Force
        Write-Host "Backed up existing $target to $target.bak"
      }
    EOT
  }
}

resource "local_file" "env" {
  depends_on = [terraform_data.env_backup]

  filename        = local.env_path
  content         = local.env_content
  file_permission = "0600"
}

output "env_local" {
  description = "Environment variables written to the repo-root .env."
  value       = local.env_content
  sensitive   = true
}
